# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('codigo_asignatura', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(blank=True, max_length=250, null=True)),
                ('guia_docente', models.CharField(blank=True, max_length=150, null=True)),
                ('curso', models.SmallIntegerField(blank=True, null=True)),
                ('regimen', models.CharField(blank=True, max_length=100, null=True)),
                ('cuatrimestre', models.CharField(blank=True, max_length=50, null=True)),
                ('creditos', models.SmallIntegerField(blank=True, null=True)),
                ('mencion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'asignaturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Centros',
            fields=[
                ('nombre_centro', models.CharField(blank=True, max_length=100, null=True)),
                ('universidad', models.CharField(blank=True, max_length=3, null=True)),
                ('campus', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_centro', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'centros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_encuestas', models.CharField(max_length=10)),
                ('grao_satisfaccion', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encuestas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImpartidaEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'impartida_en',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_tasas', models.CharField(max_length=10)),
                ('exito', models.FloatField(blank=True, null=True)),
                ('rendimiento', models.FloatField(blank=True, null=True)),
                ('evaluacion', models.FloatField(blank=True, null=True)),
                ('abandono', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titulaciones',
            fields=[
                ('codigo_titulacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_titulacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nota_corte', models.FloatField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'titulaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=80)),
                ('comentario', models.TextField()),
                ('codigo_titulacion', models.ForeignKey(blank=True, db_column='codigo_titulacion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proyecto_uni.Titulaciones')),
            ],
        ),
    ]
