# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_uni', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='titulacion',
        ),
        migrations.AddField(
            model_name='comment',
            name='codigo_titulacion',
            field=models.ForeignKey(blank=True, db_column='codigo_titulacion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proyecto_uni.Titulaciones'),
        ),
    ]
