# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_uni', '0005_auto_20160612_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comentario',
        ),
    ]
